[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
base = { path = "../base"}
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.24", features = ["json"] }