[package]
name = "base"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true}
serde_yaml = { workspace = true }
rust-crypto = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
log = { workspace = true }